//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MVVM_Demo.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_MVVM_Demo.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возраст:.
        /// </summary>
        public static string DefaultBinding_Age {
            get {
                return ResourceManager.GetString("DefaultBinding_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • CheckBox.IsChecked.
        /// </summary>
        public static string DefaultBinding_CheckBoxIsChecked {
            get {
                return ResourceManager.GetString("DefaultBinding_CheckBoxIsChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка по умолчанию (Default) автоматически выбирает режим в зависимости от ситуации:.
        /// </summary>
        public static string DefaultBinding_DescriptionText {
            get {
                return ResourceManager.GetString("DefaultBinding_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📖 Описание привязки по умолчанию (Default).
        /// </summary>
        public static string DefaultBinding_DescriptionTitle {
            get {
                return ResourceManager.GetString("DefaultBinding_DescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При изменении текста в верхнем поле, нижнее обновляется автоматически.
        /// </summary>
        public static string DefaultBinding_DirectBindingDesc {
            get {
                return ResourceManager.GetString("DefaultBinding_DirectBindingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прямая привязка к элементам интерфейса.
        /// </summary>
        public static string DefaultBinding_DirectBindingTitle {
            get {
                return ResourceManager.GetString("DefaultBinding_DirectBindingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔄 Для редактируемых свойств:.
        /// </summary>
        public static string DefaultBinding_EditableProps {
            get {
                return ResourceManager.GetString("DefaultBinding_EditableProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email:.
        /// </summary>
        public static string DefaultBinding_Email {
            get {
                return ResourceManager.GetString("DefaultBinding_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:.
        /// </summary>
        public static string DefaultBinding_FirstName {
            get {
                return ResourceManager.GetString("DefaultBinding_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное имя:.
        /// </summary>
        public static string DefaultBinding_FullName {
            get {
                return ResourceManager.GetString("DefaultBinding_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * Обновляется автоматически при изменении имени или фамилии.
        /// </summary>
        public static string DefaultBinding_FullNameDesc {
            get {
                return ResourceManager.GetString("DefaultBinding_FullNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Студент.
        /// </summary>
        public static string DefaultBinding_IsStudent {
            get {
                return ResourceManager.GetString("DefaultBinding_IsStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Label.Content.
        /// </summary>
        public static string DefaultBinding_LabelContent {
            get {
                return ResourceManager.GetString("DefaultBinding_LabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия:.
        /// </summary>
        public static string DefaultBinding_LastName {
            get {
                return ResourceManager.GetString("DefaultBinding_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Использует OneWay.
        /// </summary>
        public static string DefaultBinding_OneWayMode {
            get {
                return ResourceManager.GetString("DefaultBinding_OneWayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✅ Для свойств только для чтения:.
        /// </summary>
        public static string DefaultBinding_ReadOnlyProps {
            get {
                return ResourceManager.GetString("DefaultBinding_ReadOnlyProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • TextBlock.Text.
        /// </summary>
        public static string DefaultBinding_TextBlockText {
            get {
                return ResourceManager.GetString("DefaultBinding_TextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текстовое поле:.
        /// </summary>
        public static string DefaultBinding_TextBoxLabel {
            get {
                return ResourceManager.GetString("DefaultBinding_TextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите текст.
        /// </summary>
        public static string DefaultBinding_TextBoxPlaceholder {
            get {
                return ResourceManager.GetString("DefaultBinding_TextBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • TextBox.Text.
        /// </summary>
        public static string DefaultBinding_TextBoxText {
            get {
                return ResourceManager.GetString("DefaultBinding_TextBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст из TextBox:.
        /// </summary>
        public static string DefaultBinding_TextFromTextBox {
            get {
                return ResourceManager.GetString("DefaultBinding_TextFromTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка по умолчанию (Default).
        /// </summary>
        public static string DefaultBinding_Title {
            get {
                return ResourceManager.GetString("DefaultBinding_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Использует TwoWay.
        /// </summary>
        public static string DefaultBinding_TwoWayMode {
            get {
                return ResourceManager.GetString("DefaultBinding_TwoWayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка через ViewModel.
        /// </summary>
        public static string DefaultBinding_ViewModelBindingTitle {
            get {
                return ResourceManager.GetString("DefaultBinding_ViewModelBindingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string Language_Russian {
            get {
                return ResourceManager.GetString("Language_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор языка.
        /// </summary>
        public static string Language_Select {
            get {
                return ResourceManager.GetString("Language_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демонстрация различных типов привязок и триггеров.
        /// </summary>
        public static string MainWindow_Subtitle {
            get {
                return ResourceManager.GetString("MainWindow_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лабораторная работа №1: Виды привязок в WPF.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить?.
        /// </summary>
        public static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные успешно сохранены!.
        /// </summary>
        public static string Message_DataSaved {
            get {
                return ResourceManager.GetString("Message_DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция успешно выполнена.
        /// </summary>
        public static string Message_OperationCompleted {
            get {
                return ResourceManager.GetString("Message_OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Message_Title_Error {
            get {
                return ResourceManager.GetString("Message_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string Message_Title_Info {
            get {
                return ResourceManager.GetString("Message_Title_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        public static string Message_Title_Success {
            get {
                return ResourceManager.GetString("Message_Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string Message_Title_Warning {
            get {
                return ResourceManager.GetString("Message_Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверьте введенные данные.
        /// </summary>
        public static string Message_ValidationError {
            get {
                return ResourceManager.GetString("Message_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать в приложение!.
        /// </summary>
        public static string Message_Welcome {
            get {
                return ResourceManager.GetString("Message_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Минимальная нагрузка.
        /// </summary>
        public static string OneTimeBinding_Adv1 {
            get {
                return ResourceManager.GetString("OneTimeBinding_Adv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Не следит за изменениями.
        /// </summary>
        public static string OneTimeBinding_Adv2 {
            get {
                return ResourceManager.GetString("OneTimeBinding_Adv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Быстрая загрузка.
        /// </summary>
        public static string OneTimeBinding_Adv3 {
            get {
                return ResourceManager.GetString("OneTimeBinding_Adv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✅ Преимущества:.
        /// </summary>
        public static string OneTimeBinding_Advantages {
            get {
                return ResourceManager.GetString("OneTimeBinding_Advantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возраст:.
        /// </summary>
        public static string OneTimeBinding_Age {
            get {
                return ResourceManager.GetString("OneTimeBinding_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔄 Изменить имя в Person.
        /// </summary>
        public static string OneTimeBinding_ChangeNameButton {
            get {
                return ResourceManager.GetString("OneTimeBinding_ChangeNameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneWay Binding (для сравнения).
        /// </summary>
        public static string OneTimeBinding_ComparisonTitle {
            get {
                return ResourceManager.GetString("OneTimeBinding_ComparisonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⏰ Текущее время (OneTime):.
        /// </summary>
        public static string OneTimeBinding_CurrentTimeOneTime {
            get {
                return ResourceManager.GetString("OneTimeBinding_CurrentTimeOneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⏰ Текущее время (OneWay):.
        /// </summary>
        public static string OneTimeBinding_CurrentTimeOneWay {
            get {
                return ResourceManager.GetString("OneTimeBinding_CurrentTimeOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одноразовая привязка (OneTime) устанавливает значение один раз при создании привязки и не отслеживает последующие изменения. Это эффективно для статических данных или когда нужно показать &apos;снимок&apos; данных на момент загрузки..
        /// </summary>
        public static string OneTimeBinding_DescriptionText {
            get {
                return ResourceManager.GetString("OneTimeBinding_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📖 Описание одноразовой привязки (OneTime).
        /// </summary>
        public static string OneTimeBinding_DescriptionTitle {
            get {
                return ResourceManager.GetString("OneTimeBinding_DescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Не обновляется.
        /// </summary>
        public static string OneTimeBinding_Disadv1 {
            get {
                return ResourceManager.GetString("OneTimeBinding_Disadv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Только начальное значение.
        /// </summary>
        public static string OneTimeBinding_Disadv2 {
            get {
                return ResourceManager.GetString("OneTimeBinding_Disadv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Не подходит для динамики.
        /// </summary>
        public static string OneTimeBinding_Disadv3 {
            get {
                return ResourceManager.GetString("OneTimeBinding_Disadv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠️ Недостатки:.
        /// </summary>
        public static string OneTimeBinding_Disadvantages {
            get {
                return ResourceManager.GetString("OneTimeBinding_Disadvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✏️ Изменение данных в ViewModel.
        /// </summary>
        public static string OneTimeBinding_EditViewModel {
            get {
                return ResourceManager.GetString("OneTimeBinding_EditViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email:.
        /// </summary>
        public static string OneTimeBinding_Email {
            get {
                return ResourceManager.GetString("OneTimeBinding_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:.
        /// </summary>
        public static string OneTimeBinding_FirstName {
            get {
                return ResourceManager.GetString("OneTimeBinding_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 💡 Важно:.
        /// </summary>
        public static string OneTimeBinding_Important {
            get {
                return ResourceManager.GetString("OneTimeBinding_Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • При нажатии кнопки время в ViewModel обновляется.
        /// </summary>
        public static string OneTimeBinding_Important1 {
            get {
                return ResourceManager.GetString("OneTimeBinding_Important1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • OneTime привязка НЕ реагирует на изменения.
        /// </summary>
        public static string OneTimeBinding_Important2 {
            get {
                return ResourceManager.GetString("OneTimeBinding_Important2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Значение остается &apos;замороженным&apos;.
        /// </summary>
        public static string OneTimeBinding_Important3 {
            get {
                return ResourceManager.GetString("OneTimeBinding_Important3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия:.
        /// </summary>
        public static string OneTimeBinding_LastName {
            get {
                return ResourceManager.GetString("OneTimeBinding_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новое имя:.
        /// </summary>
        public static string OneTimeBinding_NewNameLabel {
            get {
                return ResourceManager.GetString("OneTimeBinding_NewNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новое имя.
        /// </summary>
        public static string OneTimeBinding_NewNamePlaceholder {
            get {
                return ResourceManager.GetString("OneTimeBinding_NewNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneTime Binding (Замороженные данные).
        /// </summary>
        public static string OneTimeBinding_OneTimeDemo {
            get {
                return ResourceManager.GetString("OneTimeBinding_OneTimeDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Следит за изменениями в ViewModel.
        /// </summary>
        public static string OneTimeBinding_OneWayFeat1 {
            get {
                return ResourceManager.GetString("OneTimeBinding_OneWayFeat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Автоматически обновляется.
        /// </summary>
        public static string OneTimeBinding_OneWayFeat2 {
            get {
                return ResourceManager.GetString("OneTimeBinding_OneWayFeat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Динамическое отображение.
        /// </summary>
        public static string OneTimeBinding_OneWayFeat3 {
            get {
                return ResourceManager.GetString("OneTimeBinding_OneWayFeat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✅ Особенности OneWay:.
        /// </summary>
        public static string OneTimeBinding_OneWayFeatures {
            get {
                return ResourceManager.GetString("OneTimeBinding_OneWayFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 👤 Данные Person (OneTime).
        /// </summary>
        public static string OneTimeBinding_PersonDataOneTime {
            get {
                return ResourceManager.GetString("OneTimeBinding_PersonDataOneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📋 Результат:.
        /// </summary>
        public static string OneTimeBinding_Result {
            get {
                return ResourceManager.GetString("OneTimeBinding_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • В левой колонке (OneTime) имя НЕ изменится.
        /// </summary>
        public static string OneTimeBinding_Result1 {
            get {
                return ResourceManager.GetString("OneTimeBinding_Result1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • В ViewModel данные обновились, но отображение заморожено.
        /// </summary>
        public static string OneTimeBinding_Result2 {
            get {
                return ResourceManager.GetString("OneTimeBinding_Result2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📝 Статический текст (OneTime):.
        /// </summary>
        public static string OneTimeBinding_StaticTextOneTime {
            get {
                return ResourceManager.GetString("OneTimeBinding_StaticTextOneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📝 Статический текст (OneWay):.
        /// </summary>
        public static string OneTimeBinding_StaticTextOneWay {
            get {
                return ResourceManager.GetString("OneTimeBinding_StaticTextOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одноразовая привязка (OneTime).
        /// </summary>
        public static string OneTimeBinding_Title {
            get {
                return ResourceManager.GetString("OneTimeBinding_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔄 Обновить время в ViewModel.
        /// </summary>
        public static string OneTimeBinding_UpdateTimeButton {
            get {
                return ResourceManager.GetString("OneTimeBinding_UpdateTimeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * Это значение НЕ изменится.
        /// </summary>
        public static string OneTimeBinding_ValueNotChange {
            get {
                return ResourceManager.GetString("OneTimeBinding_ValueNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * Это значение ОБНОВЛЯЕТСЯ.
        /// </summary>
        public static string OneTimeBinding_ValueUpdates {
            get {
                return ResourceManager.GetString("OneTimeBinding_ValueUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠️ Эти значения НЕ изменятся при обновлении данных.
        /// </summary>
        public static string OneTimeBinding_WarningText {
            get {
                return ResourceManager.GetString("OneTimeBinding_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возраст:.
        /// </summary>
        public static string OneWayBinding_Age {
            get {
                return ResourceManager.GetString("OneWayBinding_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔄 Изменить имя на &apos;Новое имя&apos;.
        /// </summary>
        public static string OneWayBinding_ChangeNameButton {
            get {
                return ResourceManager.GetString("OneWayBinding_ChangeNameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🎮 Управление Person в ViewModel.
        /// </summary>
        public static string OneWayBinding_ControlPersonTitle {
            get {
                return ResourceManager.GetString("OneWayBinding_ControlPersonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔢 Счетчик в ViewModel:.
        /// </summary>
        public static string OneWayBinding_CounterLabel {
            get {
                return ResourceManager.GetString("OneWayBinding_CounterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📊 Текущее значение в ViewModel:.
        /// </summary>
        public static string OneWayBinding_CurrentValueLabel {
            get {
                return ResourceManager.GetString("OneWayBinding_CurrentValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⬇️ Поток данных: источник → цель.
        /// </summary>
        public static string OneWayBinding_DataFlowDesc {
            get {
                return ResourceManager.GetString("OneWayBinding_DataFlowDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📖 Описание односторонних привязок.
        /// </summary>
        public static string OneWayBinding_DescriptionTitle {
            get {
                return ResourceManager.GetString("OneWayBinding_DescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✏️ Введи текст (обновляет ViewModel):.
        /// </summary>
        public static string OneWayBinding_EnterTextLabel {
            get {
                return ResourceManager.GetString("OneWayBinding_EnterTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:.
        /// </summary>
        public static string OneWayBinding_FirstName {
            get {
                return ResourceManager.GetString("OneWayBinding_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное имя:.
        /// </summary>
        public static string OneWayBinding_FullName {
            get {
                return ResourceManager.GetString("OneWayBinding_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⬆️ Увеличить возраст.
        /// </summary>
        public static string OneWayBinding_IncreaseAgeButton {
            get {
                return ResourceManager.GetString("OneWayBinding_IncreaseAgeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ➕ Увеличить счетчик.
        /// </summary>
        public static string OneWayBinding_IncrementButton {
            get {
                return ResourceManager.GetString("OneWayBinding_IncrementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия:.
        /// </summary>
        public static string OneWayBinding_LastName {
            get {
                return ResourceManager.GetString("OneWayBinding_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✅ Изменения в ViewModel обновляют интерфейс, но не наоборот.
        /// </summary>
        public static string OneWayBinding_OneWayDesc {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Данные текут только от источника к цели.
        /// </summary>
        public static string OneWayBinding_OneWayDesc1 {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Изменения в ViewModel обновляют UI.
        /// </summary>
        public static string OneWayBinding_OneWayDesc2 {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Изменения в UI не влияют на ViewModel.
        /// </summary>
        public static string OneWayBinding_OneWayDesc3 {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Идеально для отображения данных.
        /// </summary>
        public static string OneWayBinding_OneWayDesc4 {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✅ OneWay (ViewModel → UI).
        /// </summary>
        public static string OneWayBinding_OneWayDescTitle {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayDescTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneWay (ViewModel → UI).
        /// </summary>
        public static string OneWayBinding_OneWayTitle {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠️ Изменения в интерфейсе обновляют ViewModel, но изменения в ViewModel НЕ обновляют интерфейс.
        /// </summary>
        public static string OneWayBinding_OneWayToSourceDesc {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayToSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Данные текут от цели к источнику.
        /// </summary>
        public static string OneWayBinding_OneWayToSourceDesc1 {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayToSourceDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Изменения в UI обновляют ViewModel.
        /// </summary>
        public static string OneWayBinding_OneWayToSourceDesc2 {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayToSourceDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Изменения в ViewModel не видны в UI.
        /// </summary>
        public static string OneWayBinding_OneWayToSourceDesc3 {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayToSourceDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Полезно для сбора данных.
        /// </summary>
        public static string OneWayBinding_OneWayToSourceDesc4 {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayToSourceDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠️ OneWayToSource (UI → ViewModel).
        /// </summary>
        public static string OneWayBinding_OneWayToSourceDescTitle {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayToSourceDescTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⬆️ Поток данных: цель → источник.
        /// </summary>
        public static string OneWayBinding_OneWayToSourceFlow {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayToSourceFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneWayToSource (UI → ViewModel).
        /// </summary>
        public static string OneWayBinding_OneWayToSourceTitle {
            get {
                return ResourceManager.GetString("OneWayBinding_OneWayToSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 👤 Данные Person (OneWay).
        /// </summary>
        public static string OneWayBinding_PersonDataTitle {
            get {
                return ResourceManager.GetString("OneWayBinding_PersonDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * Обновляется при изменении в ViewModel.
        /// </summary>
        public static string OneWayBinding_PersonUpdateDesc {
            get {
                return ResourceManager.GetString("OneWayBinding_PersonUpdateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📝 Текст только для чтения:.
        /// </summary>
        public static string OneWayBinding_ReadOnlyText {
            get {
                return ResourceManager.GetString("OneWayBinding_ReadOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📋 Результат:.
        /// </summary>
        public static string OneWayBinding_Result {
            get {
                return ResourceManager.GetString("OneWayBinding_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Изменения отобразятся в левой колонке.
        /// </summary>
        public static string OneWayBinding_Result1 {
            get {
                return ResourceManager.GetString("OneWayBinding_Result1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • OneWay привязка автоматически обновит UI.
        /// </summary>
        public static string OneWayBinding_Result2 {
            get {
                return ResourceManager.GetString("OneWayBinding_Result2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • UI не может напрямую изменить эти значения.
        /// </summary>
        public static string OneWayBinding_Result3 {
            get {
                return ResourceManager.GetString("OneWayBinding_Result3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Односторонние привязки (OneWay).
        /// </summary>
        public static string OneWayBinding_Title {
            get {
                return ResourceManager.GetString("OneWayBinding_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка по умолчанию.
        /// </summary>
        public static string Tab_DefaultBinding {
            get {
                return ResourceManager.GetString("Tab_DefaultBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одноразовая привязка.
        /// </summary>
        public static string Tab_OneTimeBinding {
            get {
                return ResourceManager.GetString("Tab_OneTimeBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Односторонние привязки.
        /// </summary>
        public static string Tab_OneWayBinding {
            get {
                return ResourceManager.GetString("Tab_OneWayBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триггеры.
        /// </summary>
        public static string Tab_Triggers {
            get {
                return ResourceManager.GetString("Tab_Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двухсторонняя привязка.
        /// </summary>
        public static string Tab_TwoWayBinding {
            get {
                return ResourceManager.GetString("Tab_TwoWayBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажми для анимации.
        /// </summary>
        public static string Triggers_AnimationButton {
            get {
                return ResourceManager.GetString("Triggers_AnimationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data + Event Triggers.
        /// </summary>
        public static string Triggers_DataEventTriggers {
            get {
                return ResourceManager.GetString("Triggers_DataEventTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * Меняет цвет при IsSpecial = True.
        /// </summary>
        public static string Triggers_DataTriggerResult {
            get {
                return ResourceManager.GetString("Triggers_DataTriggerResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data Triggers.
        /// </summary>
        public static string Triggers_DataTriggers {
            get {
                return ResourceManager.GetString("Triggers_DataTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триггеры данных реагируют на изменения в данных.
        /// </summary>
        public static string Triggers_DataTriggersDesc {
            get {
                return ResourceManager.GetString("Triggers_DataTriggersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание: PropertyTrigger - на изменения свойств, DataTrigger - на данные, EventTrigger - на события.
        /// </summary>
        public static string Triggers_Description {
            get {
                return ResourceManager.GetString("Triggers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event Triggers (примеры).
        /// </summary>
        public static string Triggers_EventTriggersTitle {
            get {
                return ResourceManager.GetString("Triggers_EventTriggersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event Trigger (анимация).
        /// </summary>
        public static string Triggers_EventTriggerTitle {
            get {
                return ResourceManager.GetString("Triggers_EventTriggerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fade In.
        /// </summary>
        public static string Triggers_FadeIn {
            get {
                return ResourceManager.GetString("Triggers_FadeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hover.
        /// </summary>
        public static string Triggers_Hover {
            get {
                return ResourceManager.GetString("Triggers_Hover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наведи мышь.
        /// </summary>
        public static string Triggers_HoverButton {
            get {
                return ResourceManager.GetString("Triggers_HoverButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле ввода:.
        /// </summary>
        public static string Triggers_InputField {
            get {
                return ResourceManager.GetString("Triggers_InputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * Оранжевая подсветка при фокусе и пустом тексте.
        /// </summary>
        public static string Triggers_MultiTriggerResult {
            get {
                return ResourceManager.GetString("Triggers_MultiTriggerResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multi Triggers.
        /// </summary>
        public static string Triggers_MultiTriggers {
            get {
                return ResourceManager.GetString("Triggers_MultiTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Множественные условия.
        /// </summary>
        public static string Triggers_MultiTriggersDesc {
            get {
                return ResourceManager.GetString("Triggers_MultiTriggersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При наведении.
        /// </summary>
        public static string Triggers_OnHover {
            get {
                return ResourceManager.GetString("Triggers_OnHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При загрузке.
        /// </summary>
        public static string Triggers_OnLoad {
            get {
                return ResourceManager.GetString("Triggers_OnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажми меня.
        /// </summary>
        public static string Triggers_PressButton {
            get {
                return ResourceManager.GetString("Triggers_PressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогресс:.
        /// </summary>
        public static string Triggers_Progress {
            get {
                return ResourceManager.GetString("Triggers_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * Красный при 10, зеленый по умолчанию, желтый при 100%.
        /// </summary>
        public static string Triggers_ProgressBarResult {
            get {
                return ResourceManager.GetString("Triggers_ProgressBarResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменения при наведении и нажатии.
        /// </summary>
        public static string Triggers_PropertyTriggerResult {
            get {
                return ResourceManager.GetString("Triggers_PropertyTriggerResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property Triggers.
        /// </summary>
        public static string Triggers_PropertyTriggers {
            get {
                return ResourceManager.GetString("Triggers_PropertyTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триггеры свойств реагируют на изменения свойств элемента.
        /// </summary>
        public static string Triggers_PropertyTriggersDesc {
            get {
                return ResourceManager.GetString("Triggers_PropertyTriggersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Special Border.
        /// </summary>
        public static string Triggers_SpecialBorder {
            get {
                return ResourceManager.GetString("Triggers_SpecialBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триггеры в WPF.
        /// </summary>
        public static string Triggers_Title {
            get {
                return ResourceManager.GetString("Triggers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle Special.
        /// </summary>
        public static string Triggers_ToggleSpecialButton {
            get {
                return ResourceManager.GetString("Triggers_ToggleSpecialButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активно.
        /// </summary>
        public static string TwoWayBinding_Active {
            get {
                return ResourceManager.GetString("TwoWayBinding_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Автоматическая синхронизация.
        /// </summary>
        public static string TwoWayBinding_Adv1 {
            get {
                return ResourceManager.GetString("TwoWayBinding_Adv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Не нужно писать код обновления.
        /// </summary>
        public static string TwoWayBinding_Adv2 {
            get {
                return ResourceManager.GetString("TwoWayBinding_Adv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Данные всегда актуальны.
        /// </summary>
        public static string TwoWayBinding_Adv3 {
            get {
                return ResourceManager.GetString("TwoWayBinding_Adv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✅ Преимущества:.
        /// </summary>
        public static string TwoWayBinding_Advantages {
            get {
                return ResourceManager.GetString("TwoWayBinding_Advantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возраст:.
        /// </summary>
        public static string TwoWayBinding_Age {
            get {
                return ResourceManager.GetString("TwoWayBinding_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При изменении CheckBox, значение в ViewModel обновляется и наоборот.
        /// </summary>
        public static string TwoWayBinding_CheckBoxDesc {
            get {
                return ResourceManager.GetString("TwoWayBinding_CheckBoxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример с CheckBox (TwoWay).
        /// </summary>
        public static string TwoWayBinding_CheckBoxExample {
            get {
                return ResourceManager.GetString("TwoWayBinding_CheckBoxExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущие значения Person:.
        /// </summary>
        public static string TwoWayBinding_CurrentValues {
            get {
                return ResourceManager.GetString("TwoWayBinding_CurrentValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двухсторонняя привязка обеспечивает синхронизацию данных в обоих направлениях:.
        /// </summary>
        public static string TwoWayBinding_DescriptionText {
            get {
                return ResourceManager.GetString("TwoWayBinding_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📖 Описание двухсторонней привязки (TwoWay).
        /// </summary>
        public static string TwoWayBinding_DescriptionTitle {
            get {
                return ResourceManager.GetString("TwoWayBinding_DescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование Person (TwoWay).
        /// </summary>
        public static string TwoWayBinding_EditPerson {
            get {
                return ResourceManager.GetString("TwoWayBinding_EditPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите текст:.
        /// </summary>
        public static string TwoWayBinding_EnterText {
            get {
                return ResourceManager.GetString("TwoWayBinding_EnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • UpdateSourceTrigger влияет на момент обновления.
        /// </summary>
        public static string TwoWayBinding_Feat1 {
            get {
                return ResourceManager.GetString("TwoWayBinding_Feat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Можно отключить для оптимизации.
        /// </summary>
        public static string TwoWayBinding_Feat2 {
            get {
                return ResourceManager.GetString("TwoWayBinding_Feat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Требует INotifyPropertyChanged.
        /// </summary>
        public static string TwoWayBinding_Feat3 {
            get {
                return ResourceManager.GetString("TwoWayBinding_Feat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠️ Особенности:.
        /// </summary>
        public static string TwoWayBinding_Features {
            get {
                return ResourceManager.GetString("TwoWayBinding_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:.
        /// </summary>
        public static string TwoWayBinding_FirstName {
            get {
                return ResourceManager.GetString("TwoWayBinding_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Студент.
        /// </summary>
        public static string TwoWayBinding_IsStudent {
            get {
                return ResourceManager.GetString("TwoWayBinding_IsStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия:.
        /// </summary>
        public static string TwoWayBinding_LastName {
            get {
                return ResourceManager.GetString("TwoWayBinding_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * Обновляется в реальном времени.
        /// </summary>
        public static string TwoWayBinding_RealTimeUpdate {
            get {
                return ResourceManager.GetString("TwoWayBinding_RealTimeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на True - включено, False - выключено.
        /// </summary>
        public static string TwoWayBinding_StateDesc {
            get {
                return ResourceManager.GetString("TwoWayBinding_StateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние в ViewModel:.
        /// </summary>
        public static string TwoWayBinding_StateInViewModel {
            get {
                return ResourceManager.GetString("TwoWayBinding_StateInViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменения синхронизируются в обоих направлениях.
        /// </summary>
        public static string TwoWayBinding_SyncDesc {
            get {
                return ResourceManager.GetString("TwoWayBinding_SyncDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример с TextBox (TwoWay).
        /// </summary>
        public static string TwoWayBinding_TextBoxExample {
            get {
                return ResourceManager.GetString("TwoWayBinding_TextBoxExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст из ViewModel:.
        /// </summary>
        public static string TwoWayBinding_TextFromViewModel {
            get {
                return ResourceManager.GetString("TwoWayBinding_TextFromViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина текста:.
        /// </summary>
        public static string TwoWayBinding_TextLength {
            get {
                return ResourceManager.GetString("TwoWayBinding_TextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двухсторонняя привязка (TwoWay).
        /// </summary>
        public static string TwoWayBinding_Title {
            get {
                return ResourceManager.GetString("TwoWayBinding_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Изменение в текстовом поле.
        /// </summary>
        public static string TwoWayBinding_UIChange1 {
            get {
                return ResourceManager.GetString("TwoWayBinding_UIChange1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Переключение CheckBox.
        /// </summary>
        public static string TwoWayBinding_UIChange2 {
            get {
                return ResourceManager.GetString("TwoWayBinding_UIChange2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Выбор в ComboBox.
        /// </summary>
        public static string TwoWayBinding_UIChange3 {
            get {
                return ResourceManager.GetString("TwoWayBinding_UIChange3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Данные передаются в модель.
        /// </summary>
        public static string TwoWayBinding_UIChange4 {
            get {
                return ResourceManager.GetString("TwoWayBinding_UIChange4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⬇️ UI → ViewModel.
        /// </summary>
        public static string TwoWayBinding_UIToViewModel {
            get {
                return ResourceManager.GetString("TwoWayBinding_UIToViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⬆️ ViewModel → UI.
        /// </summary>
        public static string TwoWayBinding_ViewModelToUI {
            get {
                return ResourceManager.GetString("TwoWayBinding_ViewModelToUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Обновление данных в коде.
        /// </summary>
        public static string TwoWayBinding_VMChange1 {
            get {
                return ResourceManager.GetString("TwoWayBinding_VMChange1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Загрузка новых значений.
        /// </summary>
        public static string TwoWayBinding_VMChange2 {
            get {
                return ResourceManager.GetString("TwoWayBinding_VMChange2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Изменение состояния.
        /// </summary>
        public static string TwoWayBinding_VMChange3 {
            get {
                return ResourceManager.GetString("TwoWayBinding_VMChange3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Интерфейс обновляется.
        /// </summary>
        public static string TwoWayBinding_VMChange4 {
            get {
                return ResourceManager.GetString("TwoWayBinding_VMChange4", resourceCulture);
            }
        }
    }
}
